name: test_record
version: '${project.version}'
main: dev.tatsi.test_replay_callback.TestReplay
commands:
  startgame:
    description: "mock start game"
    usage: "/startgame"
  stopgame:
    description: "mock stop game"
    usage: "/stopgame"